# Use the latest Python 3.11
FROM python:3.11.0-alpine3.17

# Set the working directory in the container
WORKDIR /app

# Copy the source code into the container
COPY . /app

# Set the entrypoint command for the container
CMD [ "python", "main.py" ]

